version: "3"

networks:
  frontend:

volumes:
  mariadb-volume:
    driver: local
    driver_opts:
      type: 'none'
      o: 'bind'
      device: /home/ivork/Documents/codam/inception/srcs/mariadb/volume
  wordpress-volume:
    driver: local
    driver_opts:
      type: 'none'
      o: 'bind'
      device: /home/ivork/Documents/codam/inception/srcs/wordpress/site


services:
  mariadb:
      container_name: "mariadb"
      build: ./mariadb
      restart: unless-stopped
      networks:
        - frontend
      volumes:
        - mariadb-volume:/var/lib/mysql
      env_file:
        - .env

  wordpress:
      container_name: "wordpress"
      build: ./wordpress
      restart: always
      expose:
        - 9000
      networks:
        - frontend
      depends_on:
        - mariadb
      ports:
        - 9000:9000
      volumes:
        - wordpress-volume:/var/www/
      env_file:
        - .env

  nginx:
      container_name: "nginx"
      build: ./nginx
      depends_on:
        - wordpress
      restart: on-failure
      volumes:
        - wordpress_volume:/var/www/
      ports:
        - "443:443"
      networks:
        - frontend
      env_file:
        - .env